# 과제 2
    데이터 : "7.세종시_아파트(전월세)_실거래가.csv"
    1) 세종시 데이터에서 컬럼 확인 후, unnamed 컬럼 제거
    2) 전월세구분 컬럼에서 unique값 확인  
    3) index= 100~200, column = 전월세구분, 전용면적(㎡),보증금(만원)으로 이루어진 데이터프레임 추출 
    4) 0~200 index를 가진 행 삭제 
    5) 건축년도 컬럼 중복 제거 결과 출력

In [3]:
import pandas as pd

In [112]:
sejong = pd.read_csv("data/7.세종시_아파트(전월세)_실거래가.csv")

In [113]:
sejong

,Unnamed: 0,계약년월,계약일,시군구,본번,부번,단지명,전월세구분,전용면적(㎡),보증금(만원),월세(만원),층,건축년도
0,0,201701,13,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,10000,0,13,2015
1,1,201701,14,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,18000,0,19,2015
2,2,201701,14,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,59.8338,17000,0,10,2015
3,3,201701,15,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,17000,0,2,2015
4,4,201702,4,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),월세,84.9895,10000,30,13,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38890,38890,202011,21,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,102.8300,10000,100,5,2020
38891,38891,202012,8,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,102.5300,10000,95,14,2020
38892,38892,202012,11,세종특별자치시 해밀동,6402,1,해밀마을 2단지,전세,84.9500,30000,0,18,2020
38893,38893,202012,12,세종특별자치시 해밀동,6402,1,해밀마을 2단지,전세,84.9500,34000,0,18,2020
38894,38894,202012,13,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,84.9500,8000,85,16,2020

In [114]:
# 1) 세종시 데이터에서 컬럼 확인 후, unnamed 컬럼 제거
sejong.columns
sejong.drop(columns = ['Unnamed: 0'], inplace = True)
# sejong.drop('Unnamed: 0', axis = 1, inplace = True)

In [115]:
sejong

,계약년월,계약일,시군구,본번,부번,단지명,전월세구분,전용면적(㎡),보증금(만원),월세(만원),층,건축년도
0,201701,13,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,10000,0,13,2015
1,201701,14,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,18000,0,19,2015
2,201701,14,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,59.8338,17000,0,10,2015
3,201701,15,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,17000,0,2,2015
4,201702,4,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),월세,84.9895,10000,30,13,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
38890,202011,21,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,102.8300,10000,100,5,2020
38891,202012,8,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,102.5300,10000,95,14,2020
38892,202012,11,세종특별자치시 해밀동,6402,1,해밀마을 2단지,전세,84.9500,30000,0,18,2020
38893,202012,12,세종특별자치시 해밀동,6402,1,해밀마을 2단지,전세,84.9500,34000,0,18,2020
38894,202012,13,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,84.9500,8000,85,16,2020

In [116]:
# 2) 전월세구분 컬럼에서 unique값 확인
sejong['전월세구분'].unique()

array(['전세', '월세'], dtype=object)

In [117]:
# 3) index= 100~200, column = 전월세구분, 전용면적(㎡),보증금(만원)으로 이루어진 데이터프레임 추출 
sejong_2 = sejong.loc[100:200, ['전월세구분', '전용면적(㎡)','보증금(만원)']]
sejong_2

    전월세구분  전용면적(㎡)  보증금(만원)
100    전세  73.7130    13000
101    월세  73.7130     1200
102    전세  84.9837    15000
103    전세  73.7130    11000
104    전세  73.7130    10000
..    ...      ...      ...
196    전세  59.9917     8000
197    전세  59.9917    11000
198    월세  84.9894     1000
199    전세  84.9894    15000
200    전세  59.9917    12000

[101 rows x 3 columns]

In [118]:
sejong_2 = sejong.iloc[100:201, 6:9] # numeric 기반, 반열림(끝 미포함)
sejong_2

    전월세구분  전용면적(㎡)  보증금(만원)
100    전세  73.7130    13000
101    월세  73.7130     1200
102    전세  84.9837    15000
103    전세  73.7130    11000
104    전세  73.7130    10000
..    ...      ...      ...
196    전세  59.9917     8000
197    전세  59.9917    11000
198    월세  84.9894     1000
199    전세  84.9894    15000
200    전세  59.9917    12000

[101 rows x 3 columns]

In [121]:
#4) 0~200 index를 가진 행 삭제 
sejong_3 = sejong
sejong_3.drop(sejong_3.index[0:201], inplace = True)

In [127]:
#5) 건축년도 컬럼 중복 제거 결과 출력
sejong.drop_duplicates(['건축년도']) # 중복된 건축년도의 행중 첫 번째 행만 추출

,계약년월,계약일,시군구,본번,부번,단지명,전월세구분,전용면적(㎡),보증금(만원),월세(만원),층,건축년도
201,201707,29,세종특별자치시 고운동,1393,0,가락마을15단지(중흥파크뷰),월세,59.9917,1000,40,3,2015
473,201701,6,세종특별자치시 고운동,1708,0,가락마을3단지(호반베르디움),전세,84.9893,21000,0,6,2014
1898,201701,4,세종특별자치시 금남면 용포리,320,0,두진리버빌,전세,59.8676,10000,0,15,2000
1973,201702,3,세종특별자치시 금남면 용포리,263,0,신성연기미소지움,전세,84.8768,14000,0,12,2007
1996,201707,13,세종특별자치시 나성동,732,0,세종모닝시티2차,월세,25.4322,300,30,5,2016
1998,201705,30,세종특별자치시 나성동,712,0,세종퍼스트타워,월세,28.4520,300,34,5,2013
2019,201711,14,세종특별자치시 나성동,730,0,에스알파크시티,전세,24.2700,8000,0,7,2017
2036,201711,28,세종특별자치시 다정동,960,0,가온마을1단지,전세,59.9843,12000,0,13,2018
2039,201710,18,세종특별자치시 다정동,920,0,가온마을9단지,월세,84.9400,6100,60,12,2019
2826,201701,26,세종특별자치시 도담동,848,0,도램마을8단지(행복1차아파트),월세,40.5800,303,6,7,2012
4180,201705,25,세종특별자치시 부강면 부강리,498,7,대신하나로,전세,59.8600,3500,0,6,2002
4184,201706,10,세종특별자치시 부강면 부강리,401,48,주연,월세,59.8200,500,30,6,1992
4186,201704,15,세종특별자치시 부강면 부강리,970,3,청솔,월세,49.8300,1000,30,8,1994
6480,201701,5,세종특별자치시 연동면 명학리,255,0,다산청정,전세,41.3280,2500,0,10,2001
6535,201709,6,세종특별자치시 전의면 동교리,213,28,성호늘푸른,전세,59.7600,5000,0,13,1997
6538,201705,28,세종특별자치시 전의면 동교리,121,6,"재동(1,2동)",월세,58.8800,1000,30,4,1991
6551,201701,18,세종특별자치시 조치원읍 교리,11,1,계룡,월세,59.2800,1000,40,1,1989
6563,201708,31,세종특별자치시 조치원읍 남리,456,0,다원파크리안,전세,83.2560,11000,0,11,2003
6564,201705,11,세종특별자치시 조치원읍 남리,377,0,청송,월세,25.2500,300,20,2,1996
6823,201701,4,세종특별자치시 조치원읍 신흥리,398,0,신흥대우푸르지오,월세,104.9044,3000,55,3,2006
6839,201701,3,세종특별자치시 조치원읍 신흥리,393,0,신흥주공,월세,49.2900,1000,40,18,1999
6880,201701,4,세종특별자치시 조치원읍 신흥리,399,0,조치원 신흥 e편한세상(아),월세,118.1980,15000,12,9,2008
6936,201708,10,세종특별자치시 조치원읍 정리,59,1,풍산,전세,59.7500,7000,0,13,1998
8404,201701,2,세종특별자치시 한솔동,939,0,첫마을1단지(퍼스트프라임),월세,59.8300,2000,55,7,2011
15189,201804,5,세종특별자치시 조치원읍 원리,2,3,대도,전세,66.9000,5000,0,3,1980
19801,201905,27,세종특별자치시 다정동,965,0,가온마을7단지,월세,37.1200,1828,20,2,2020
33640,202009,9,세종특별자치시 부강면 부강리,976,2,대광,전세,59.4000,3000,0,3,1988

In [132]:
sejong[sejong['건축년도'] == 2000]

,계약년월,계약일,시군구,본번,부번,단지명,전월세구분,전용면적(㎡),보증금(만원),월세(만원),층,건축년도
1898,201701,4,세종특별자치시 금남면 용포리,320,0,두진리버빌,전세,59.8676,10000,0,15,2000
1899,201701,9,세종특별자치시 금남면 용포리,320,0,두진리버빌,전세,59.8676,10000,0,8,2000
1900,201701,10,세종특별자치시 금남면 용포리,320,0,두진리버빌,월세,43.0080,300,40,8,2000
1901,201701,13,세종특별자치시 금남면 용포리,320,0,두진리버빌,전세,43.0080,6500,0,2,2000
1902,201701,17,세종특별자치시 금남면 용포리,320,0,두진리버빌,전세,43.0080,6500,0,4,2000
...,...,...,...,...,...,...,...,...,...,...,...,...
29194,202012,16,세종특별자치시 금남면 용포리,320,0,두진리버빌,전세,43.0080,6800,0,4,2000
29195,202012,18,세종특별자치시 금남면 용포리,320,0,두진리버빌,월세,59.8676,1000,52,1,2000
29196,202012,23,세종특별자치시 금남면 용포리,320,0,두진리버빌,월세,43.0080,500,45,14,2000
29197,202012,30,세종특별자치시 금남면 용포리,320,0,두진리버빌,전세,43.0080,14000,0,10,2000
29198,202012,31,세종특별자치시 금남면 용포리,320,0,두진리버빌,전세,43.0080,14000,0,8,2000